// Global App States
export const UPDATE_IS_APP_LOADING = 'UPDATE_IS_APP_LOADING';
export const UPDATE_APP_LOCALE = 'UPDATE_APP_LOCALE';
export const UPDATE_SHOW_USERS_WITHOUT_GROUPS = 'UPDATE_SHOW_USERS_WITHOUT_GROUPS';
export const UPDATE_APP_CONFIG = 'UPDATE_APP_CONFIG';
export const UPDATE_IS_LOGGING = 'UPDATE_IS_LOGGING';
export const UPDATE_IS_DISCONNECTED = 'UPDATE_IS_DISCONNECTED';
export const UPDATE_XMPP_CLIENT = 'UPDATE_XMPP_CLIENT';
export const UPDATE_CHAT_TIMESTAMP = 'UPDATE_CHAT_TIMESTAMP';

// Auth User
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER';
export const UPDATE_AUTH_USER_PRESENCE = 'UPDATE_AUTH_USER_PRESENCE';
export const UPDATE_AUTH_USER_IMAGE_BIN = 'UPDATE_AUTH_USER_IMAGE_BIN';

// Roster List
export const UPDATE_ROSTER_LIST = 'UPDATE_ROSTER_LIST';
export const UPDATE_ROSTER_OBJ = 'UPDATE_ROSTER_OBJ';
export const UPDATE_PRESENCE_ROSTER_CONTACT = 'UPDATE_PRESENCE_ROSTER_CONTACT';
export const UPDATE_STATUS_ROSTER_CONTACT = 'UPDATE_STATUS_ROSTER_CONTACT';
export const ADD_TO_ROSTER_LIST = 'ADD_TO_ROSTER_LIST';
export const UPDATE_IS_LOADING_ROSTER = 'UPDATE_IS_LOADING_ROSTER';

// Profile Image
export const UPDATE_PROFILE_IMAGE_LIST = 'UPDATE_PROFILE_IMAGE_LIST';
export const UPDATE_PROFILE_IMAGE_BIN = 'UPDATE_PROFILE_IMAGE_BIN';
export const UPDATE_PROFILE_IMAGE_HASH = 'UPDATE_PROFILE_IMAGE_HASH';
export const ADD_PROFILE_IMAGE_TO_LIST = 'ADD_PROFILE_IMAGE_TO_LIST';
export const REMOVE_PROFILE_IMAGE_FROM_LIST = 'REMOVE_PROFILE_IMAGE_FROM_LIST';
