// Chatbox Global States
export const UPDATE_CHATBOX_EMOJI = 'UPDATE_CHATBOX_EMOJI';
export const UPDATE_LAST_NOTIFICATION = 'UPDATE_LAST_NOTIFICATION';
export const UPDATE_CHAT_CONFIG = 'UPDATE_CHAT_CONFIG';
export const UPDATE_NUM_UNREAD_CONVERSATION = 'UPDATE_NUM_UNREAD_CONVERSATION';
export const UPDATE_LAST_MESSAGE_SENT_STAMP = 'UPDATE_LAST_MESSAGE_SENT_STAMP';
export const UPDATE_IS_PRESENCE_AWAY = 'UPDATE_IS_PRESENCE_AWAY';
export const UPDATE_LAST_PRESENCE = 'UPDATE_LAST_PRESENCE';

// Conversation List
export const ADD_CONVERSATION_TO_LIST = 'ADD_CONVERSATION_TO_LIST';
export const UPDATE_CONVERSATION_LIST = 'UPDATE_CONVERSATION_LIST';
export const REORDER_CONVERSATION_LIST = 'REORDER_CONVERSATION_LIST';
export const REMOVE_CONVERSATION_FROM_LIST = 'REMOVE_CONVERSATION_FROM_LIST';
export const REORDER_CONVERSATIONS_BY_CONVERSATION = 'REORDER_CONVERSATIONS_BY_CONVERSATION';

// Conversation
export const ADD_MESSAGE_TO_CONVERSATION = 'ADD_MESSAGE_TO_CONVERSATION';
export const CLEAR_UNREAD_COUNTER_CONVERSATION = 'CLEAR_UNREAD_COUNTER_CONVERSATION';
export const PLUS_UNREAD_COUNTER_CONVERSATION = 'PLUS_UNREAD_COUNTER_CONVERSATION';
export const SET_CHATBOX_STATE_CONVERSATION = 'SET_CHATBOX_STATE_CONVERSATION';
export const UPDATE_ACTIVE_CONVERSATION = 'UPDATE_ACTIVE_CONVERSATION';
export const UPDATE_ACTIVE_CONVERSATION_IS_TYPING = 'UPDATE_ACTIVE_CONVERSATION_IS_TYPING';

// Old Conversation
export const UPDATE_OLD_CONVERSATION = 'UPDATE_OLD_CONVERSATION';
export const UPDATE_OLD_CONVERSATION_LAST_STAMP = 'UPDATE_OLD_CONVERSATION_LAST_STAMP';
export const UPDATE_OLD_CONVERSATION_NO_RESULT = 'UPDATE_OLD_CONVERSATION_NO_RESULT';
export const UPDATE_OLD_CONVERSATION_LAST_RETRIEVED_ID = 'UPDATE_OLD_CONVERSATION_LAST_RETRIEVED_ID';
export const UPDATE_OLD_CONVERSATION_LAST_MESSAGE_ID = 'UPDATE_OLD_CONVERSATION_LAST_MESSAGE_ID';
export const ADD_MESSAGE_LIST_TO_OLD_CONVERSATION = 'ADD_MESSAGE_LIST_TO_OLD_CONVERSATION';
export const UPDATE_LOCK_AUTO_LOAD_OLD_MESSAGES = 'UPDATE_LOCK_AUTO_LOAD_OLD_MESSAGES';
export const CLEAR_OLD_CONVERSATION = 'CLEAR_OLD_CONVERSATION';